### PR TITLE
[ADD] add docs for Auto-GPT integration

### PR DESCRIPTION
**Pull request by afbenevides**
added DOCS  that will fit the modifications for

 https://github.com/Significant-Gravitas/Auto-GPT/pull/2594 

from 

https://github.com/DGdev91/Auto-GPT

works on my side.

### CODE REVIEW

**Comment by keldenl** [comment]
does this actually work? i dont see the base_url or embed_dim environment variables

**Comment by keldenl** [comment]
did you mean to say use the fork from this PR https://github.com/Significant-Gravitas/Auto-GPT/pull/2594? if so then please update the readme and i'll go ahead and merge

**Comment by afbenevides** [comment]
> did you mean to say use the fork from this PR [Significant-Gravitas/Auto-GPT#2594](https://github.com/Significant-Gravitas/Auto-GPT/pull/2594)? if so then please update the readme and i'll go ahead and merge

Yes you are right its not clear

**Review by keldenl — APPROVED** [review]
LGTM

**Pull request merged**
